@baseAddress = http://localhost:5101

###
POST {{baseAddress}}/api/v1/files
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="hello-world.txt"
Content-Type: text/plain

Hello World
------WebKitFormBoundary--
###
DELETE {{baseAddress}}/api/v1/files
Content-Type: application/json
{
"fileName": "bee5d70c-e889-464e-9a98-1d977bf08af7.txt"
}
###