@baseAddress = http://localhost:5238
@categoryId = 08dd8139-d165-593e-dc1b-a105a5fa0000
@courseId = 08dd81d2-84d0-c538-dc1b-a105a5fa0000
@userId = a5fa0000-a105-dc1b-7add-08dd85f39646

GET {{baseAddress}}/api/categories
Accept: application/json
###

Post {{baseAddress}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "name": "Category1"
}
###

GET {{baseAddress}}/api/categories/{{categoryId}}
Accept: application/json
###


POST {{baseAddress}}/api/courses
Content-Type : application/json
Accept : application/json
{
  "name": "New Course 3",
  "description": "This is a new course",
  "categoryId": "{{categoryId}}",
  "price": 10,
  "imageUrl": "https://example.com/image.jpg"
}
###
PUT {{baseAddress}}/api/courses
Content-Type : application/json
Accept : application/json
{
  "Id": "{{courseId}}",
  "name": "New Course 333",
  "description": "This is a new course 333",
  "categoryId": "{{categoryId}}",
  "price": 999,
  "imageUrl": "https://example.com/image2.jpg"
}
###


GET {{baseAddress}}/api/courses
Accept: application/json
###

GET {{baseAddress}}/api/courses/{{courseId}}
Accept: application/json
###
DELETE {{baseAddress}}/api/courses/{{courseId}}
Accept: application/json
###

GET {{baseAddress}}/api/courses/user/{{userId}}
Accept: application/json
###
